### ISSUE TITLE
Suggestion: keep on/off Drawable's on their position

### ISSUE THREAD

**Issue by fardavide** [ngallazzi/FancySwitch#1]
_I have to say I didn't try the lib, I'm basing my suggestion of the previews I see on Readme, I'm sorry if the final behavior has changed_

I think that forcing the replacement of both icons with the "current state" Drawable is pretty confusional, I would keep the on/off Drawable's on their original position: the position and color of the switch would be pretty self-explanatory of the current state.

**Comment by ngallazzi** [comment]
Hi @4face-studi0, thanks for your feedback. Probably you're right and it would be a more intuitive behavior to make the dragging button icon match with the current state. My initial idea was to set the icon on the dragging button accordingly to the "state  to reach", but probably that's confusing for users. Thanks for your support, I will include the edit you suggested in the next release!
