### ISSUE TITLE
How change status ON/OFF 

### ISSUE THREAD

**Issue by raul1525** [ngallazzi/FancySwitch#11]
Indicate the initial status (ON / OFF) of the programming
This is possible

Example:
vFancySwitch!!.setState(FancyState.State.ON)

**Comment by ngallazzi** [comment]
Hi @raul1525, yes there is a method on FancySwitch class:

`override fun setState(newState: FancyState.State) {
        currentState = when (newState) {
            FancyState.State.ON -> stateOn
            FancyState.State.OFF -> stateOff
        }

        requestLayout()

        if (::changeListener.isInitialized) {
            changeListener.onChanged(currentState)
        }
    }`

You can call the method whenever you like in your code. I've just updated the readme with instructions ;)

**Comment by raul1525** [comment]
Hi @ngallazzi  thank's  👍

**Comment by ngallazzi** [comment]
Closing the issue, thanks for using the library 😊
