### ISSUE TITLE
Pull Request #3 Broke the Switch Margin

### ISSUE THREAD

**Issue by arunavo4** [ngallazzi/FancySwitch#4]
@ngallazzi After #3  this change, the Switch now looks out of place.
[Current Look 8dp Margin](https://pasteboard.co/JHEQ5kG.png)
[Before 16dp Margin](https://pasteboard.co/JHER7I9.png)

**Comment by ngallazzi** [comment]
Thank you @arunavo4, just fixed on master branch. Can you confirm please?

**Comment by arunavo4** [comment]
Yup fixed
