### ISSUE TITLE
[Feature Request] setState Method Needs animation.

### ISSUE THREAD

**Issue by arunavo4** [ngallazzi/FancySwitch#6]
When using setState Method there is no animation.

**Comment by ngallazzi** [comment]
Thank you for the feature request, I'll surely work on it ;)

**Comment by ngallazzi** [comment]
@arunavo4 just merged the request on master branch ;), let me know if the new feature works for you :)

**Comment by arunavo4** [comment]
@ngallazzi  Wow, that was fast. Thanks a lot, it works well

**Comment by ngallazzi** [comment]
You're very welcome. Thanks for pointing me on the issue! I'm going to fix
the scrolling problem soon too, I'll let you know when fixed!

See you soon,

Nicola

Il mer 13 gen 2021, 07:33 ARUNAVO RAY <notifications@github.com> ha scritto:
